# Generated by Django 5.2.7 on 2025-10-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('energy_used', models.FloatField()),
                ('co2_emission', models.FloatField()),
            ],
        ),
    ]
