# Generated by Django 5.2.7 on 2025-10-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energydata',
            name='co2_emission',
        ),
        migrations.RemoveField(
            model_name='energydata',
            name='energy_used',
        ),
        migrations.AddField(
            model_name='energydata',
            name='emission',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='energydata',
            name='energy_consumed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='energydata',
            name='steps',
            field=models.IntegerField(default=0),
        ),
    ]
